@extends('Backend.Layout.App')
@section('content')

 <div class="main-content">
        <!-- Header -->
        <div class="header">
            <div class="search-bar">
                <i class="fas fa-search"></i>
                <input type="text" placeholder="Search for food, orders, customers...">
            </div>
            <div class="user-profile">
                <div class="notifications">
                    <i class="fas fa-bell"></i>
                </div>
                <img src="https://randomuser.me/api/portraits/men/32.jpg" alt="User">
                <span>John Doe</span>
            </div>
        </div>

        <!-- Dashboard Cards -->
        <div class="dashboard-cards">
            <div class="card stat-card">
                <div class="icon orders-icon">
                    <i class="fas fa-clipboard-list"></i>
                </div>
                <div class="info">
                    <h3>128</h3>
                    <p>Total Orders</p>
                </div>
            </div>
            <div class="card stat-card">
                <div class="icon revenue-icon">
                    <i class="fas fa-dollar-sign"></i>
                </div>
                <div class="info">
                    <h3>$4,562</h3>
                    <p>Total Revenue</p>
                </div>
            </div>
            <div class="card stat-card">
                <div class="icon customers-icon">
                    <i class="fas fa-user-friends"></i>
                </div>
                <div class="info">
                    <h3>562</h3>
                    <p>Total Customers</p>
                </div>
            </div>
            <div class="card stat-card">
                <div class="icon rating-icon">
                    <i class="fas fa-star"></i>
                </div>
                <div class="info">
                    <h3>4.8</h3>
                    <p>Average Rating</p>
                </div>
            </div>
        </div>

        <!-- Charts and Recent Orders -->
        <div class="charts-orders">
            <div class="chart-container">
                <div class="chart-header">
                    <h2>Revenue Overview</h2>
                    <select>
                        <option>Last 7 Days</option>
                        <option>Last 30 Days</option>
                        <option>Last 90 Days</option>
                    </select>
                </div>
                <div class="chart" id="revenueChart">
                    <!-- Chart bars will be generated by JavaScript -->
                </div>
            </div>
            <div class="recent-orders">
                <div class="chart-header">
                    <h2>Recent Orders</h2>
                    <a href="#">View All</a>
                </div>
                <div class="orders-list">
                    <div class="order-item">
                        <img src="https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=400&q=80" alt="Pizza">
                        <div class="order-info">
                            <h4>Margherita Pizza</h4>
                            <p>Order #1234 • $12.99</p>
                        </div>
                        <div class="order-status delivered">Delivered</div>
                    </div>
                    <div class="order-item">
                        <img src="https://images.unsplash.com/photo-1563379926898-05f4575a45d8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=400&q=80" alt="Burger">
                        <div class="order-info">
                            <h4>Classic Burger</h4>
                            <p>Order #1235 • $9.99</p>
                        </div>
                        <div class="order-status preparing">Preparing</div>
                    </div>
                    <div class="order-item">
                        <img src="https://images.unsplash.com/photo-1513104890138-7c749659a591?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=400&q=80" alt="Pasta">
                        <div class="order-info">
                            <h4>Spaghetti Marinara</h4>
                            <p>Order #1236 • $14.99</p>
                        </div>
                        <div class="order-status preparing">Preparing</div>
                    </div>
                    <div class="order-item">
                        <img src="https://images.unsplash.com/photo-1603893662172-99ed0bba5a6e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=400&q=80" alt="Salad">
                        <div class="order-info">
                            <h4>Caesar Salad</h4>
                            <p>Order #1237 • $8.99</p>
                        </div>
                        <div class="order-status cancelled">Cancelled</div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Popular Items -->
        <h2 style="margin-bottom: 20px;">Popular Items</h2>
        <div class="popular-items">
            <div class="food-card">
                <img src="https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=400&q=80" alt="Pizza">
                <div class="food-info">
                    <h3>Margherita Pizza</h3>
                    <p>Classic cheese and tomato</p>
                    <div class="price">$12.99</div>
                </div>
            </div>
            <div class="food-card">
                <img src="https://images.unsplash.com/photo-1563379926898-05f4575a45d8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=400&q=80" alt="Burger">
                <div class="food-info">
                    <h3>Classic Burger</h3>
                    <p>Beef patty with veggies</p>
                    <div class="price">$9.99</div>
                </div>
            </div>
            <div class="food-card">
                <img src="https://images.unsplash.com/photo-1513104890138-7c749659a591?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=400&q=80" alt="Pasta">
                <div class="food-info">
                    <h3>Spaghetti Marinara</h3>
                    <p>Fresh seafood pasta</p>
                    <div class="price">$14.99</div>
                </div>
            </div>
            <div class="food-card">
                <img src="https://images.unsplash.com/photo-1603893662172-99ed0bba5a6e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=400&q=80" alt="Salad">
                <div class="food-info">
                    <h3>Caesar Salad</h3>
                    <p>Fresh greens with dressing</p>
                    <div class="price">$8.99</div>
                </div>
            </div>
        </div>
    </div>
@endsection